# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd017c87f93f2d372108aef5017d130e62cc8a96651f3e3ff47dbd7d5ba6c8c777105c6faff1bf5ffc84f8bcc1d165e3ea679356966249c357b7c9622730f127

test:
  secret_key_base: 0a8809387d704ae76df1adcd01dd97c835d76c6089cd59ae6ad4f9a3e8add7be0bc87d257ad978c12f9ed20796ca90b80b0368749e452cfb2329bfa47604039d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
